### ISSUE TITLE
How to generate a gif from a Vimeo URL

### ISSUE THREAD

**Issue by tcocca** [gifs/api#13]
Does the API support links to Vimeo video urls?

I'm trying

```
curl -X POST -H "Gifs-API-Key: gifsXXXXXXXXXXXXXX" -H "Content-Type: application/json" -d '{
  "source": "https://vimeo.com/3449553",
  "trim": {
    "start": 0,
    "end": 4
 }
}' "https://api.gifs.com/media/import"
```

and that is giving errors

Is there a different format for the vimeo URL i need to use?

**Comment by kieranoreilly** [comment]
It looks like Vimeo changed their video format making it unable to be processed. Apologies
