### ISSUE TITLE
XMLHttpRequest error for upload

### ISSUE THREAD

**Issue by leandromatos** [gifs/api#4]
The api does not support upload from other servers? I tried to upload a gif that's in my server but I get the error:

`XMLHttpRequest can not load https://api.gifs.com/media/import. Response to preflight request does not pass access control check: In the 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://is-uz.com' is Therefore not allowed access.`

**Comment by montanaflynn** [comment]
Hey @leandromatos thanks for the issue, the problem has been fixed and your request should work now.

Example: http://jsbin.com/hefurajaha/edit?js,console

**Comment by leandromatos** [comment]
With import endpoint, all right, now seems to have an error with the upload. See the response:

`"We've encountered an unexpected issue, please try again."`

**Comment by odeke-em** [comment]
Ping @leandromatos, could you try again? We've done quite a bit of work behind the scenes.

**Comment by leandromatos** [comment]
@odeke-em On here, that's fine, I tested right now!

**Comment by odeke-em** [comment]
Cool. Thanks for checking in. Does the issue still exist?

**Comment by leandromatos** [comment]
@odeke-em If I find an error, I notice you! Thanks
