### ISSUE TITLE
Search API

### ISSUE THREAD

**Issue by antonlvovych** [gifs/api#7]
Hello :v:

What do you think about adding an API for searching gifs?

**Comment by montanaflynn** [comment]
Hey @geekiam that's definitely something we have thought about, no concrete plans just yet though!

**Comment by antonlvovych** [comment]
@montanaflynn I love gifs.com so let me know if you need help with anything. I'll be pleased to contribute :neckbeard:

**Comment by kieranoreilly** [comment]
Thanks @geekiam
